#!/bin/sh

invalid="Please enter a valid input"

cat << "EOF"

------------------------------
-. .-.   .-. .-.   .-. .-.   .
  \   \ /   \   \ /   \   \ /
 / \   \   / \   \   / \   \
~   `-~ `-`   `-~ `-`   `-~ `-
  _            _           
 |_  |   _   _|_  |  o   _ 
 |   |  (_)   |   |  |  _> 
                           
        PACKAGER

------------------------------

EOF

#echo "- Linking NodeJS modules..."
#ln -s /1/Floflis/libs/node_modules node_modules

#echo "Do you want to install node modules? [Y/n]"
#while true; do
#read installnodemodules
#case $installnodemodules in
#   [nN])
#       echo "${ok}"
#       break ;;
#   [yY])
#       echo "- Installing NodeJS modules for this app..."
#       sudo npm install -g
#   *)
#       echo "${invalid}";;
#esac
#done

#echo "Is this a Construct 2 game/app? [Y/n]"
#while true; do
#read itsconstruct2
#case $itsconstruct2 in
#   [nN])
#       echo "${ok}"
#       break ;;
#   [yY])
#       echo ""
#       echo "(!) Detected this app/game uses Construct 2 engine. Applying special patch for C2..."
#       chmod +x /usr/lib/floflis/packager/optionals/construct-2/c2init.sh && ./usr/lib/floflis/packager/optionals/construct-2/c2init.sh
#   *)
#       echo "${invalid}";;
#esac
#done

#echo "(✓) Done! Your app is ready."

if [ "$1" = "init" ]; then
   sh /usr/lib/floflis/packager/./init.sh
fi

if [ "$1" = "pack" ]; then
   sh /usr/lib/floflis/packager/./pack.sh
fi

#if [ "$1" = "c2" ] || [ "$1" = "construct" ]; then
if [ "$1" = "c2" ]; then
   if [ "$2" = "pre-export" ]; then
      sh /usr/lib/floflis/packager/optionals/construct-2/./pre-export
   fi
   if [ "$2" = "initpreview" ]; then
      sh /usr/lib/floflis/packager/optionals/construct-2/./initpreview
   fi
fi
