#!/bin/bash

source_exportsfolder="$(jq -r '.floflispackager.exportsfolder' manifest.webapp)"
source_rootfolder="$(echo $PWD)"
#running_notfrom_exportsfolder="true"
#export running_notfrom_exportsfolder
#if [ -f "$source_exportsfolder/pre-initpreview" ]; then
#   sh $source_exportsfolder/./pre-initpreview
#fi
cd "$source_exportsfolder"
if [ -f "$source_exportsfolder/pre-initpreview" ]; then sh $source_exportsfolder/./pre-initpreview; fi
cd "$source_rootfolder"
#cd "$source_exportsfolder"
floflis-packager init
#sh /usr/lib/floflis/packager/./init.sh

if [ -f *".caproj" ]; then
   writefrom_caproj_name="$(cat *.caproj | grep -oE ".?name[^<>]*>[^<>]+" | cut -d'>' -f2 | head -2 | tail -2 | tr -d '[:cntrl:]')"
   # credits about using  | tr -d '[:cntrl:]' https://stackoverflow.com/questions/23816264/remove-all-special-characters-and-case-from-string-in-bash#comment59852614_23816607
   writefrom_caproj_description="$(cat *.caproj | grep -oE ".?description[^<>]*>[^<>]+" | cut -d'>' -f2 | head -2 | tail -2 | tr -d '[:cntrl:]')"
   writefrom_caproj_version="$(cat *.caproj | grep -oE ".?version[^<>]*>[^<>]+" | cut -d'>' -f2 | head -2 | tail -1)"
   writefrom_caproj_author="$(cat *.caproj | grep -oE ".?author[^<>]*>[^<>]+" | cut -d'>' -f2 | head -2 | tail -2 | tr -d '[:cntrl:]')"
   #writefrom_caproj_authoremail="$(cat *.caproj | grep -oE ".?author-email[^<>]*>[^<>]+" | cut -d'>' -f2 | head -2 | tail -2 | tr -d '[:cntrl:]')"
   writefrom_caproj_authorwebsite="$(cat *.caproj | grep -oE ".?author-website[^<>]*>[^<>]+" | cut -d'>' -f2 | head -2 | tail -2 | tr -d '[:cntrl:]')"
   #writefrom_caproj_appid="$(cat *.caproj | grep -oE ".?app-id[^<>]*>[^<>]+" | cut -d'>' -f2 | head -2 | tail -2 | tr -d '[:cntrl:]')"
   
   contents="$(jq ".name = \"$writefrom_caproj_name\"" manifest.webapp)" && \
   echo "${contents}" > manifest.webapp
   contents="$(jq ".description = \"$writefrom_caproj_description\"" manifest.webapp)" && \
   echo "${contents}" > manifest.webapp
   contents="$(jq ".version = \"$writefrom_caproj_version\"" manifest.webapp)" && \
   echo "${contents}" > manifest.webapp
   contents="$(jq ".developer.name = \"$writefrom_caproj_author\"" manifest.webapp)" && \
   echo "${contents}" > manifest.webapp
   contents="$(jq ".developer.url = \"$writefrom_caproj_authorwebsite\"" manifest.webapp)" && \
   echo "${contents}" > manifest.webapp
fi

cd "$source_exportsfolder"
npm start
